---
title: Tidy Tuesday, Week 25
author: Ellen Gibbs
date: 18/06/2019
output: 
  html_document:
    css: "./../gitstyles.css"
---

```{r set-up hook, include=FALSE}
hook_in <- function(x, options) {
    x <- x[!grepl("^#\\s+", x)]
    paste0("```r\n",
          paste0(x, collapse="\n"),
          "\n```")
}
# knitr::knit_hooks$set(source = hook_in)
```

```{r loading, include=FALSE, message=FALSE, results='hide'}
library(tidyverse)

bird_counts <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-18/bird_counts.csv")

# str(bird_counts)
# View(bird_counts)
```

```{r Analysis, warning=FALSE, message=FALSE}
Count_per_year_species <- bird_counts %>% 
  group_by(year, species) %>% 
  summarise(num_count = sum(how_many_counted)) %>% 
  arrange(species)

Diff_count <- Count_per_year_species %>% 
  group_by(species) %>% 
  summarise(variation = (max(num_count) - min(num_count))) %>% 
  arrange(desc(variation))

Count_per_year_species <- Count_per_year_species %>% 
  mutate(species = factor(species, levels = Diff_count$species)) %>% 
  arrange(species)
```

```{r Plotting, echo=1:2}
a <- 1; b <- 5
ggplot(data = Count_per_year_species[((a-1)*94 + 1):(b*94),], 
       aes(x = year, y = num_count, group = species, colour = species)) + 
  geom_line() + 
  labs(x = "Year", y = "Number Seen/Heard per Year", colour = "Species", 
       title = "Number of Each Species Seen/Heard per Year in Ontario, Canada",
       subtitle = "Top Five Varying Species")

# ggplot(data = Diff_count) + 
#   geom_line(aes(x = seq_along(variation), y = variation))
# 
# ggplot(data = Count_per_year_species[1:94,], 
#        aes(x = year, y = num_count, group = species, colour = species)) + 
#   geom_line()
# 
# plot(Diff_count$variation, type='l')

```